package controller;

import javax.swing.JFrame;
import javax.swing.JPanel;

import model.IntegratedSensorSuite;
/**
 * The console mode that will display the highs and lows of the sensors.
 * @author chanteltrainer
 */
public class HighsAndLowsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -132530797963607835L;
    
    private JFrame myWindow;
    private JPanel myHomePanel;
    private IntegratedSensorSuite myISS;
    
    /**
     * Creates new form HighsAndLowsMode
     */
    public HighsAndLowsPanel(JFrame theJFrame, JPanel theHomePanel, IntegratedSensorSuite theISS) {
        myWindow = theJFrame;
        myHomePanel = theHomePanel;
        myISS = theISS;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                      
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ViewPanel = new javax.swing.JPanel();
        label_WindSpeed = new javax.swing.JLabel();
        textField_WindSpeed = new javax.swing.JTextField();
        label_Temperature = new javax.swing.JLabel();
        textField_Temperature = new javax.swing.JTextField();
        label_Humidity = new javax.swing.JLabel();
        textField_Humidity = new javax.swing.JTextField();
        label_Rain = new javax.swing.JLabel();
        textField_Rain = new javax.swing.JTextField();
        label_UV = new javax.swing.JLabel();
        textField_UV = new javax.swing.JTextField();
        label_CurrentWeather = new javax.swing.JLabel();
        button_Home = new javax.swing.JButton();
        button_DayHighs = new javax.swing.JButton();
        button_DayLows = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(160, 213, 253));

        ViewPanel.setBackground(new java.awt.Color(223, 241, 254));

        label_WindSpeed.setText("Wind Speed:");

        textField_WindSpeed.setEditable(false);
        textField_WindSpeed.setBorder(null);
        textField_WindSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_WindSpeedActionPerformed(evt);
            }
        });

        label_Temperature.setText("Temperature:");

        textField_Temperature.setEditable(false);
        textField_Temperature.setBorder(null);
        textField_Temperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_TemperatureActionPerformed(evt);
            }
        });

        label_Humidity.setText("Humidity:");

        textField_Humidity.setEditable(false);
        textField_Humidity.setBorder(null);
        textField_Humidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_HumidityActionPerformed(evt);
            }
        });

        label_Rain.setText("Rain (in/hr):");

        textField_Rain.setEditable(false);
        textField_Rain.setBorder(null);
        textField_Rain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_RainActionPerformed(evt);
            }
        });

        label_UV.setText("UV Radiation:");

        textField_UV.setEditable(false);
        textField_UV.setBorder(null);
        textField_UV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_UVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addComponent(label_Temperature)
                                .addGap(32, 32, 32))
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_WindSpeed)
                                    .addComponent(label_Humidity))
                                .addGap(18, 18, 18)))
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_Humidity, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(textField_WindSpeed)
                            .addComponent(textField_Temperature)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewPanelLayout.createSequentialGroup()
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Rain)
                            .addComponent(label_UV))
                        .addGap(30, 30, 30)
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_UV)
                            .addComponent(textField_Rain))))
                .addGap(71, 71, 71))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_WindSpeed)
                    .addComponent(textField_WindSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Temperature)
                    .addComponent(textField_Temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Humidity)
                    .addComponent(textField_Humidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Rain)
                    .addComponent(textField_Rain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_UV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_UV))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        label_CurrentWeather.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        label_CurrentWeather.setText("Highs and Lows Mode");

        button_Home.setText("Home");
        button_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HomeActionPerformed(evt);
            }
        });

        button_DayHighs.setText("Day Highs");
        button_DayHighs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DayHighsActionPerformed(evt);
            }
        });

        button_DayLows.setText("Day Lows");
        button_DayLows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DayLowsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_Home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_CurrentWeather)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_DayHighs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_DayLows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_CurrentWeather)
                    .addComponent(button_Home))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(button_DayHighs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_DayLows))
                    .addComponent(ViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        

    private void button_HomeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        myWindow.setContentPane(myHomePanel);
        myWindow.pack();
    }                                           

    private void textField_UVActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textField_RainActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void textField_HumidityActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void textField_TemperatureActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void textField_WindSpeedActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void button_DayHighsActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    	System.out.println("Day High Triggered");
    	
        textField_WindSpeed.setText(myISS.myWindSpeed.getWindHigh());
        textField_Temperature.setText(myISS.myTemperature.getTempHigh());
        textField_Humidity.setText(myISS.myHumidity.getHumidityHigh());
        textField_Rain.setText(myISS.myRainSensor.getRainHigh());
        textField_UV.setText(myISS.myUVSensor.getRadiationHigh());
    }                                               

    private void button_DayLowsActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	System.out.println("Day Low Triggered");
    	
    	textField_WindSpeed.setText(myISS.myWindSpeed.getWindLow());
        textField_Temperature.setText(myISS.myTemperature.getTempLow());
        textField_Humidity.setText(myISS.myHumidity.getHumidityLow());
        textField_Rain.setText(myISS.myRainSensor.getRainLow());
        textField_UV.setText(myISS.myUVSensor.getRadiationLow());
    }                                              


    // Variables declaration - do not modify                     
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JButton button_DayHighs;
    private javax.swing.JButton button_DayLows;
    private javax.swing.JButton button_Home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_CurrentWeather;
    private javax.swing.JLabel label_Humidity;
    private javax.swing.JLabel label_Rain;
    private javax.swing.JLabel label_Temperature;
    private javax.swing.JLabel label_UV;
    private javax.swing.JLabel label_WindSpeed;
    private javax.swing.JTextField textField_Humidity;
    private javax.swing.JTextField textField_Rain;
    private javax.swing.JTextField textField_Temperature;
    private javax.swing.JTextField textField_UV;
    private javax.swing.JTextField textField_WindSpeed;
    // End of variables declaration                   
}
                

